query GetProductos($page:Int,$number_paginate:Int,$estado:String){
  GetProductos(page:$page,number_paginate:$number_paginate,estado:$estado) {
    NroItems
    data {
      id
      nombre
      slug
      descripcionCorta
      descripcionLarga
      foto_real {
        id
        nombre
        url
      }
      open_graph {
        id
        nombre
        url
      }
      galeria {
        id
        nombre
        url
      }
      keywords
      favoritos
      estado
      categoria_producto_id
      created_at
      updated_at
      data {
        id
        nombre
        slug
        estado
        keywords
        descripcion
        imagen{
          id
          nombre
          url
        }
        open_graph{
           id
          nombre
          url
        }
        created_at
        updated_at
      }
      ProductoTallas {
        id
        precio_real
        precio_descuento
        stock_minimo
        stock_real
        talla_id
        Talla{
          id
          nombreTalla
        }
      }
    }
  }
}